
image:
  file: .gitpod.dockerfile
  context: .env
  
ports:
- port: 8080
  onOpen: open-preview
- port: 9003
  onOpen: ignore

tasks:
- name: Apache
  init: >
    sudo cp .env/apache.conf /etc/apache2/apache2.conf &&
    sudo cp .env/xdebug_cli.ini /etc/php/8.2/cli/conf.d/99-custom.ini &&
    sudo cp .env/xdebug_web.ini /etc/php/8.2/apache2/conf.d/99-custom.ini
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log

vscode:
  extensions:
    - felixfbecker.php-debug